core_home:
    path:      /
    defaults:
        _controller: CoreBundle:Default:index

login_user:
    resource: "@CoreBundle/Controller/LoginController.php"
    type:     annotation

directory_user:
    resource: "@CoreBundle/Controller/DirectoryController.php"
    type:     annotation

file_user:
    resource: "@CoreBundle/Controller/FileController.php"
    type:     annotation


core_user:
    resource: "@CoreBundle/Controller/UserController.php"
    type:     annotation
