services:
#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    core_bundle.userprovider:
        class: CoreBundle\Security\User\WebserviceUserProvider
        arguments:
            - "@lexik_jwt_authentication.encoder"
            - "@doctrine.orm.entity_manager"