first:
    path:      /
    defaults:
        _controller: AppBundle:Default:index
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /app

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /webservice

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
