app_home:
    path:      /
    defaults:
        _controller: AppBundle:Default:index

app_index:
    path:      /home
    defaults:
        _controller: AppBundle:Home:index

app_login:
    path:      /login
    defaults:
        _controller: AppBundle:Home:toLogin

app_index_user:
    path:      /myaccount
    defaults:
        _controller: AppBundle:Home:indexUser

app_dropzone:
    path:      /upload
    defaults:
        _controller: AppBundle:Home:toDropzone

app_download:
    path:      /download
    defaults:
        _controller: AppBundle:Home:downloadFile

app_delete:
    path:      /delete
    defaults:
        _controller: AppBundle:Home:deleteFile
