app_home:
    path:      /
    defaults:
        _controller: AppBundle:Default:index

app_index:
    path:      /home
    defaults:
        _controller: AppBundle:Home:index

app_login:
    path:      /login
    defaults:
        _controller: AppBundle:Home:toLogin

app_index_user:
    path:      /user/home
    defaults:
        _controller: AppBundle:Home:indexUser

app_dropzone:
    path:      /user/dropzone
    defaults:
        _controller: AppBundle:Home:toDropzone

