<?php

namespace CoreBundle\Repository;
use CoreBundle\Entity\Directory;

/**
 * DirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUserFolder($user) {

        $em = $this->getEntityManager()
            ->createQuery(/** @Lang text */
                "SELECT d FROM CoreBundle\Entity\Directory d 
                     JOIN CoreBundle\Entity\User u 
                     WHERE d.user = u.id
                     AND d.user = :user
                     ORDER BY d.id")
            ->setParameter('user',$user)
            //->getSQL();
           ->getResult();

        return $em;


    }

}
