<?php

namespace CoreBundle\Repository;
use CoreBundle\Entity\Directory;
use Doctrine\ORM\AbstractQuery;


/**
 * DirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectoryRepository extends \Doctrine\ORM\EntityRepository
{


   public function getFolderAndFiles($folder):array {

       $em = $this->createQueryBuilder('d')
           ->select('d,f')
           ->join('d.files','f')
           ->where('d.id = :folder')
           ->setParameter('folder',$folder)
           ->getQuery()
           ->getResult(AbstractQuery::HYDRATE_ARRAY);


       return $em;
   }


    public function getUserRootDir($userId)
   {
       return $this->createQueryBuilder('d')
           ->select('d')
           ->where('d.user = :userId')
           ->andWhere('d.parent is NULL')
           ->setParameter('userId', $userId)
           ->getQuery()
           ->getSingleResult();
   }


}
