<?php

namespace CoreBundle\Repository;
use Doctrine\ORM\AbstractQuery;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Doctrine\ORM\EntityRepository
{

}
