<?php

namespace CoreBundle\Repository;
use CoreBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUsernameOrEmail(String $username):User
    {
        $em = $this->getEntityManager()
            ->createQuery( /** @lang text */
                "SELECT u FROM CoreBundle\Entity\User u
                     WHERE  u.username = :username OR u.email = :email
                    ")
            ->setParameter('username',$username)
            ->setParameter('email', $username)
            ->getSingleResult();

        return $em;
    }
}
